backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folders: "static/uploads"

collections:
  - name: "code"
    label: "Coding"
    folder: "content/coding"
    create: true
    slug: "{{year}}--{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true, default: "HI"}
      
